server:
  port: 8080
logging:
  level:
    root: warn
    '[com.scuzzyfox]': debug

spring:
  datasource:
    username: sqladmin
    password: 7uk9DrcA^QPa
    url: jdbc:mysql://localhost:3306/test


  main:
    allow-circular-references: true